# 生产环境配置
# 服务端口
server:
  port: 5001
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jianzhang_new?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: Bincool!..
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置redis
  redis:
    database: 1 # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    password: ItIsRedis1234
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 0 # 连接池中的最小空闲连接 默认 0
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

wechat:
  appId: wx34xxxasdf123
  appSecret: sdaf1234234saffgd